# =============================================================================
# Terraform-docs Configuration File for Modules Only
# =============================================================================
# Purpose: Configure automated documentation generation for Terraform modules
# Scope: Only generates documentation for modules/, NOT root directory
# Usage: terraform-docs reads this file to determine output format and content
# =============================================================================

# =============================================================================
# OUTPUT FORMAT CONFIGURATION
# =============================================================================
formatter: "markdown table"

# =============================================================================
# RECURSIVE PROCESSING CONFIGURATION
# =============================================================================
# Only process modules directory, never the root
recursive:
  enabled: true
  path: modules

# =============================================================================
# SECTION VISIBILITY CONFIGURATION
# =============================================================================
sections:
  hide: []
  show: []

# =============================================================================
# DOCUMENTATION CONTENT TEMPLATE  
# =============================================================================
content: |-
  {{ .Header }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  {{ .Modules }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  {{ .Footer }}

# =============================================================================
# OUTPUT FILE CONFIGURATION
# =============================================================================
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# =============================================================================
# CONTENT GENERATION SETTINGS
# =============================================================================
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true