name: Generate Terraform Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/**/*.tf'
      - 'environments/**/*.tf'
      - '.terraform-docs.yml'
  workflow_dispatch:

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Install terraform-docs
        run: |
          TERRAFORM_DOCS_VERSION="0.18.0"
          curl -sSLo terraform-docs.tar.gz "https://terraform-docs.io/dl/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz"
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/
          rm terraform-docs.tar.gz
          terraform-docs --version

      - name: Generate documentation using script
        run: |
          chmod +x scripts/generate-docs.sh
          ./scripts/generate-docs.sh

      - name: Commit documentation updates
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --staged --quiet; then
            echo "No documentation changes to commit"
          else
            git commit -m "docs: update module and environment documentation [skip ci]"
            echo "Documentation changes committed"
          fi

      - name: Push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if git log --oneline -1 | grep -q "docs: update"; then
            git push origin main || echo "Push failed - this may be expected in forks or with insufficient permissions"
          else
            echo "No documentation changes to push"
          fi